colors:
  bg: "#16161d"
  bg_rgb: "22, 22, 29"
  fg: "#fdf6e3"
  accent: "#009CA6"
  red: "#D50032"
  yellow: "#DAAA00"
  blue: "#00afff"
  magenta: "#C6007E"
  orange: "#D86018"
  green: "#008000"
  opacity: "0.68"
