#!/bin/sh
# Profile file. Runs on login. Environmental variables are set here.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$(du "$HOME/.local/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
export PATH="$PATH:/home/diego/.scripts"
export PATH="$PATH:/opt/depot_tools"
export PATH="$PATH:/home/diego/.gem/ruby/2.7.0/bin"
export PATH="$PATH:/home/diego/.cargo/bin/bender"

#export LARBSWM="i3"
# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"
export READER="zathura"
export FILE="ranger"
export PAGER="less"
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"



# Clean-up:
export NOTMUCH_CONFIG="$HOME/.config/notmuch-config"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export ZDOTDIR="$HOME/.config/zsh"
#export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"

export QSYS_ROOTDIR="/home/diego/.cache/yay/quartus-free/pkg/quartus-free-quartus/opt/intelFPGA/23.1/quartus/sopc_builder/bin"
