#!/bin/bash

num=$(i3-msg -t get_workspaces | jq '.[0].num')
output=$(i3-msg -t get_workspaces | jq '.[0].output')
extd=0
while [ "$num" != "null" ]
do
	extd=$((extd+1))
	if [ $output = "\"eDP-1-1\"" ] && [ $num -gt 5 ]
		then
			i3-msg "workspace $num; move workspace to output right"
			extd=0
	fi
	filter1=".[$extd].num"
	filter2=".[$extd].output"
	num=$(i3-msg -t get_workspaces | jq $filter1)
	output=$(i3-msg -t get_workspaces | jq $filter2)
done

#filter=".[$extd].current_workspace"
#ws=$(i3-msg -t get_outputs | jq $filter)
#
#echo $ws
#for i in 6 7 8 9 10
#do
#	if [ "\"$i\"" != $ws ]
#	then
#		echo $i
#	   i3-msg "workspace $i; move workspace to output left"
#	fi
#done

#i3-msg "workspace 9; workspace 6"
#sleep(2)
#i3-msg "workspace 9; workspace 1"

#for i in 6 7 8 9 10
#do
#	name=$(i3-msg -t get_outputs | jq '.[0].name')
#	
#	if [ "\"$i\"" != $ws ]
#	then
#		echo $i
#	   i3-msg "workspace $i; move workspace to output left"
#	fi
#done
#
#num=$(i3-msg -t get_workspaces | jq '.[0].num')
#output=$(i3-msg -t get_workspaces | jq '.[0].output')
#
#count=0
#while [ "$num" !=  "null" ]
#do
#	if [ $num -gt 5 ]
#	then
#		if [ $output = "\"
#		echo $name
#		break;
#	fi
#	extd=$((i+1))
#	filter=".[$extd].name"
#	name=$(i3-msg -t get_outputs | jq $filter)
#done
#
#filter=".[$extd].current_workspace"
#ws=$(i3-msg -t get_outputs | jq $filter)
